app = "my-telegram-bot"
primary_region = "ams"

[build]
  builder = "docker"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[mounts]
  source = "bot_data"
  destination = "/app/bd"